services:
  api-gateway:
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
      target: runner
    env_file:
      - path: ./apps/api-gateway/.env
        required: false
    ports:
      - "${API_PORT:-3002}:3002"

  ground-station:
    build:
      context: .
      dockerfile: ./apps/ground-station/Dockerfile
      target: runner
    env_file:
      - path: ./apps/ground-station/.env
        required: false
    ports:
      - "${GROUND_STATION_PORT:-9001}:9001"
    depends_on:
      - kafka