services:
  api-gateway:
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
      target: runner
    env_file:
      - path: ./apps/api-gateway/.env
        required: false
    ports:
      - "${API_PORT:-3002}:3002"

  geo-transponder:
    build:
      context: .
      dockerfile: ./apps/geo-transponder/Dockerfile
      target: runner
    ports:
      - "${TRANSPONDER_PORT:-9001}:9001"
    depends_on:
      - kafka